import type { Lesson } from '../types';

export const LESSONS: Lesson[] = [
  {
    id: 'home-row-1',
    title: 'Home Row Heroes',
    description: 'Master the home row keys: ASDF JKL;',
    icon: '⌨️',
    category: 'home_row',
    words: ['asd', 'jkl', 'dad', 'fall', 'hall', 'jak', 'ask', 'sad', 'lad', 'flask', 'slash', 'flash', 'shall', 'allay', 'salad'],
  },
  {
    id: 'home-row-2',
    title: 'Finger Power',
    description: 'Build muscle memory with key combinations',
    icon: '💪',
    category: 'home_row',
    words: ['add', 'all', 'lass', 'fall', 'hall', 'flag', 'half', 'glad', 'alga', 'gala', 'saga', 'lash', 'dash', 'cash', 'rash'],
  },
  {
    id: 'common-1',
    title: 'Super Short Words',
    description: 'Practice the most common 3-letter words',
    icon: '🌟',
    category: 'common_words',
    words: ['the', 'and', 'for', 'are', 'but', 'not', 'you', 'all', 'any', 'can', 'had', 'her', 'was', 'one', 'our'],
  },
  {
    id: 'common-2',
    title: 'Word Warrior Basics',
    description: 'Type common words at lightning speed!',
    icon: '⚡',
    category: 'common_words',
    words: ['that', 'with', 'have', 'this', 'will', 'your', 'from', 'they', 'know', 'want', 'been', 'good', 'much', 'some', 'time'],
  },
  {
    id: 'common-3',
    title: 'Sentence Starters',
    description: '5-letter words to boost your speed',
    icon: '🚀',
    category: 'common_words',
    words: ['about', 'after', 'again', 'below', 'could', 'every', 'first', 'found', 'great', 'house', 'large', 'learn', 'never', 'other', 'place'],
  },
  {
    id: 'speed-1',
    title: 'Speed Blaster!',
    description: '30-second sprint - type as fast as you can!',
    icon: '🔥',
    category: 'speed_drill',
    targetWPM: 30,
    words: ['cat', 'dog', 'run', 'fast', 'jump', 'high', 'low', 'big', 'small', 'fire', 'ice', 'wind', 'star', 'moon', 'sun', 'sky', 'land', 'sea', 'air', 'day'],
  },
  {
    id: 'speed-2',
    title: 'Turbo Typist',
    description: 'Mixed words speed challenge - 45 seconds!',
    icon: '⚡',
    category: 'speed_drill',
    targetWPM: 45,
    words: ['brave', 'light', 'power', 'quick', 'blaze', 'crash', 'drive', 'flash', 'ghost', 'hyper', 'laser', 'magic', 'ninja', 'quest', 'storm'],
  },
  {
    id: 'speed-3',
    title: 'Keyboard Legend',
    description: 'Hard words speed challenge - go pro!',
    icon: '👑',
    category: 'speed_drill',
    targetWPM: 60,
    words: ['quantum', 'eclipse', 'fracture', 'voltage', 'phantom', 'blazing', 'crystal', 'digital', 'execute', 'gateway', 'kinetic', 'maximum', 'network', 'protect', 'victory'],
  },
];
